baseURL = "https://techviti-test.netlify.app/"
disableLanguages = [""]
disqusShortname = "themefisher-template"
googleAnalytics = ""
paginate = "6"
summaryLength = "10"
theme = "agico-hugo"
title = "Agico | App Landing Hugo Template"
[markup.goldmark.renderer]
unsafe = true
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON"]
